backend:
  name: github
  repo: VercaNiCa/VercaNiCa.github.io
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posty"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Treść", name: "body", widget: "markdown"}
